### ISSUE TITLE
could you provide the tool to convert BFM2017 ？

### ISSUE THREAD

**Issue by ForrestPi** [berksaribas/face-reconstruction#2]
I have dowbloaded model2017-1_bfm_nomouth.h5  but the number of vertex and triangle not match the number in your code
could you provide the tool to convert BFM2017 ？

**Comment by berksaribas** [comment]
Hi,

You need model2017-1_face12_nomouth.h5. The tool simply converted the required parts of the h5 file to binary format.

**Comment by ForrestPi** [comment]
@berksaribas thanks
